---
title: "Purpose"
author: "KartikTrivedi"
date: "11/16/2017"
output:
    bookdown::gitbook: default
documentclass: book
---

# Purpose

The Demand Side RRTC partnered with the Alabama Department of Rehabilitation Services beginning in 2012 to infuse labor market information into a dashboard for counselors and to assist the ADRS to expand the programmatic use of formal labor market data to better serve jobseekers, understand business needs, and project long-term training solutions. Early on in the effort, it became very apparent that there are many sources of data and each have advantages and limitations for use in VR. The RRTC created this catalogue as a guide for selecting data elements and understanding the range of possible data sources. Since 2012, Congress passed the Workforce Innovation and Opportunity Act of 2014 that requires state VR agencies to use LMI. We expanded this catalogue and made it available to all state VR agencies as a handy reference for exploration. The Demand Side RRTC partnered with the RSA funded Job Driven Vocational Rehabilitation Technical Assistance Center to solicit review and recommendations to expand the catalogue. We included more information about how to access LMI within different states and provided some sample analyses that may be relevant for VR agencies. 

This catalogue is divided in two sections. In the first section we will describe LMI using common definitions and discuss different types of LMI and different ways of appreciating LMI. In the second section we catalogue different sources of LMI available at the time fo this report. The catalogue highlights critical LMI sources that have a high likelihood of relevance to state VR agencies. More data sources are likely to be available over time and will be added to the catalogue. 

Note: We make no conclusion about whether or not any given data source should be or should not be used by VR. We assert that VR agencies should select sources that have use for the particular goal in mind. Yet, we acknowledge that with an increase in readily available LMI data, there is a high likelihood that VR personnel may become overwhelmed with options. We hold to the belief that wise use of data is better than simply increasing the number of data sources used.  
Hopefully this manual will help VR to tease out relevant information from a multitude information available to them.

