---
title: "What is LMI"
author: "KartikTrivedi"
date: "11/16/2017"
output:
    bookdown::gitbook: default
documentclass: book
---

# What is LMI?
According to the Bureau of Labor Statistics (2017), LMI is essential for tracking and analyzing the economy of a country. National and local governments need labor market information to reduce unemployment, generate employment, or plan training programs to meet the needs of industry. It is also used in determining future workforce training needs, identifying the availability of labor, ascertaining prevailing wage rates, exploring potential markets.  LMI encompasses a wide array of measures that can help describe an economy. Some of the primary examples are unemployment rates, occupational statistics and employment projections. Below is the list of common domains that tend to fall in broad categories such as general economic indicators, labor force descriptors, and occupational skills clusters.

- Employment and unemployment data or forecasts
-	Wage and hours worked data
-	Industry sector data including trends, such as job growth or decline
-	Occupation data including trends such as  job growth or decline 
-	Labor turnover and mobility
-	Average hours worked per week
-	General economic trends such as gross domestic product (GDP).

Arguably, there are three major types of sources of LMI. 

- Traditional LMI
- Real-Time LMI
- Labor Market Intelligence

## Sources of LMI
Different sources of LMI mostly gather data in different ways and oftne provide exclusively different types of information. Therefore, it is important to appreciate their difference and the value they bring to the VR and decision making. 

### Traditional LMI
Traditional LMI can be defined as a broad array of data on the labor market that is systematically collected, analyzed and reported by the government agencies. This data is made available free of cost by the government. Traditional LMI sources covers wide range of geographical area, depending upon which level of government collected the data. Key data metrics include current employment levels, projected employment growth, unemployment rates, average wages, minimum education requirements, industry trends, and workforce demographics.

### Real-Time LMI
Real-time LMI is the data generated from job postings posted online. Such information is derived from job-postings or resumes that are posted online and can be obtained at a very granular level for different localities. Real-time LMI is “scraped” concurrently from different sources rather than compiled over long periods of time from surveys or other data collection methods. Like traditional LMI, real-time LMI can provide information on labor market trends such as wages, skills in demand and emerging occupations or sectors.

### Labor Market Intelligence
Labor Market Intelligence is data gathered by VR employees from employers, chambers of commerce, and industry associations about opportunities and challenges of hiring for different positions, expected changes in employment, and positions that require specialized skills. Labor Market Intelligence can often be very local in nature – i.e., providing labor market information for a particular set of employers in a town. In comparison, Traditional LMI has to be aggregated at relatively larger geographical unit. Labor Market Intelligence generated by VR employees uses existing social networks by including different stakeholders.