---
title: "Why Use LMI?"
author: "KartikTrivedi"
date: "11/16/2017"
output:
    bookdown::gitbook: default
documentclass: book
---

# Why Labor Market Information May Be Useful For State VR Agencies

State VR Agencies may find multiple uses for LMI at the administrative, field services, and counselor levels. With the passage of WIOA, state VR agencies and technical assistance providers are searching for ways to integrate LMI into their work. State VR agencies such as the Alabama Department of Rehabilitation Services are testing different methods.  

LMI provides a big picture of labor market trends at the national, state and local levels, and projects future outlook. By using LMI VR agencies may be able to more effectively prepare demand-side strategic efforts and respond to labor market needs. 

VR agencies could use LMI to:

- Serve clients with disabilities, while considering the following points: 
    - Demographic characteristics of the population
    - Prevalent wages for certain occupation and industry
    - In-demand skills and education
    - Need for re-location and commuting 
-	Meet employer’s needs, while keeping the following points into account:
    - Number of openings and mean salaries by industry and occupation 
    - Job openings during a particular period of the year
    - Develop business partnership with key business players
- Improve strategic planning efforts
