---
title: "Public Data Source"
author: "KartikTrivedi"
date: "November 28, 2017"
output:
    bookdown::gitbook: default
documentclass: book
---

# Public Sources of LMI

## The U.S. Department of Labor

“The Bureau of Labor Statistics of the U.S. Department of Labor is the principal Federal agency responsible for measuring labor market activity, working conditions, and price changes in the economy.” Its mission is to collect, analyze, and disseminate  essential economic information to support public and private decision-making. The data disseminated by the BLS is mainly gathered from surveys that are administered monthly (e.g., Mass Layoff Statistics), quarterly (e.g., Quarterly Census of Employment and Wages), and annually (e.g., National Longitudinal Surveys.) (U.S. Bureau of Labor Statistics 2017e).

### The Current Employment Statistics (CES)
<http://www.bls.gov/ces/> (National Database)

<https://www.bls.gov/sae/data.htm> (State and Metro Area Database)

Current Employment Statistics (CES) survey, is based on a survey of approximately 147,000 businesses and government agencies representing approximately 634,000 worksites throughout the United States. The primary statistics derived from the survey are monthly estimates of employment, hours, and earnings for the Nation, States, and major metropolitan areas. Preliminary National estimates for a given reference month are typically released on the third Friday after the conclusion of the reference period in conjunction with data derived from a separate survey of households, the Current Population Survey (CPS). The reference period for the CES survey is the pay period which includes the 12th of the month. (U.S. Bureau of Labor Statistics 2017)

**Strengths:** The CES tracks hours worked and earnings (e.g., average hourly earnings, average weekly hours, and average weekly overtime hours). CES data are classified according to the 2012 North American Industry Classification System (NAICS), which streamlines the industry classification process. CES data is updated every month thus VR employees can track changes in the state labor market on a regular basis.

**Limitations:** The CES collects data on non-agricultural industries only. The data are aggregated at the industry level (e.g., average hourly earnings). The CES does not provide any county-level data, and only metro areas covered in regional analysis. For a state VR agency any analysis based on CES will be limited to the state level.

**Level of specificity:** The CES is published on a monthly basis at the national level. This dataset gives an overview of the health of the economy in the United States.

### The Quarterly Census of Employment and Wages (QCEW)

<http://www.bls.gov/cew/>

The QCEW is a complete count of employment and wages, classified by industry and based on quarterly reports filed by employers for over 7 million establishments subject to unemployment insurance laws. This data can be used to calculate the number of establishments, monthly employment, and quarterly wages, by industry, by county, and for the entire country.(U.S. Bureau of Labor Statistics 2017d)

**Strengths:** Original source of QCEW is the Quarterly Contributions Report (QCRs) submitted to State Workforce Agencies (SWAs) by employers subjected to unemployment insurance laws. This data is not collected from individual institutions. Collected from SWAs this data is an accurate reflection of UI data. The QCEW publishes a quarterly count of employment and wages reported by employers covering 98 percent of U.S jobs. State VR agencies can get granular data at a county level on number of establishments , monthly employment, and quarterly wages.

**Limitations:** Wage data are available on a quarterly basis only. The QCEW does not collect data from the self-employed, domestic workers, and unpaid family workers.

**Level of specificity:** The information provided by this dataset is available at the county, Metropolitan Statistical Area, state and national levels by industry.


### The Local Area Unemployment Statistics (LAUS)

<http://www.bls.gov/lau/>

LAUS is source of monthly and annual estimates for employment, unemployment, and labor force data for census divisions, states, counties, metropolitan areas, and cities. These data are available for 7,500 areas and can be used to assess localized labor markets and perform comparative analysis across regions.(U.S. Bureau of Labor Statistics 2017c)

**Strengths:** General strength of the LAUS is that it allows you to identify unemployment trends at the country or city level (for some states). 

**Limitations:** The LAUS only looks at unemployment rates, and cannot be used in conjunction with any other data source. For example, one cannot find unemployment rates for any particular industry or occupation. Therefore there is no way to connect it with any other source of LMI.

**Level of specificity:** The LAUS produces data for census regions, divisions, states, counties, metropolitan areas, cities with a population of 25,000 or more and for all cities in the New England area.

### The Occupational Employment Statistics (OES)

<http://www.bls.gov/oes/>

The OES program produces annual employment and wage estimates for over 800 occupations and 400 industries. BLS provides these estimates at national, state and at metropolitan and nonmetropolitan geographical levels. The OES also has occupational estimates for over 450 industry classification. This data is collected by surveying approximately 200,000 establishments every six months. (U.S. Bureau of Labor Statistics 2017c)

**Strengths:** The OES can be used to analyze occupational employment, occupational wages, and occupational projections. The OES can be used as tool by VR counselors during counseling by talking about occupational trends in the state or local region. The OES can also be used in conjunction with RSA 911 data by using Standard Occupation Codes (SOC) as a key variable. 

**Limitations:** Covers full-time and part-time non-farm industries only and does not include self-employment, owners and partners in unincorporated firms, household workers, or unpaid family workers. 

**Level of specificity:** Estimates are available at the national and state levels, and for selected metropolitan and nonmetropolitan regions.

### The Mass Layoff Statistics (MLS)

<http://www.bls.gov/mls/>

The MLS collects information on mass layoff actions. The information is gathered using a combination of each state’s unemployment insurance databases and employer-provided data. Monthly mass layoff numbers are collected from establishments from which a minimum of 50 claims for unemployment insurance has been made during a five-week period. A quarterly version of this dataset is also available.(U.S. Bureau of Labor Statistics 2017d)

**Strengths:** MLS data are available on a monthly basis. In addition to monthly reports, one can find quarterly and annual data. The MLS can be used to look at the characteristics of dislocated workers by their age, race, sex, ethnic group and place of residence. These variables can help understand labor demand on monthly basis. Additionally, this is the only source of data to find reasons for separation between employee and employer, which could be useful to see if any particular industry is performing poorly.

**Limitations:** MLS data are only a subset of all layoff activity. Many layoffs fail to meet the qualifying criteria. For example, large layoffs accompanied by low levels of unemployment insurance activity may not be identified as an MLS event. 

**Level of specificity:** Data generated from the MLS is available at the state and industry level.

### Business Employment Dynamics (BED)

<http://www.bls.gov/bdm/home.htm>

BED data are generated from the Quarterly Census Employment and Wages program. This data source includes quarterly measurements of gross job gains and gross job losses. (U.S. Bureau of Labor Statistics 2017a)

**Strengths:** Using the BED, you can estimate gross job gains and gross job losses in a particular establishment. Therefore, you can estimate which establishments are opening, closing, expanding, or contracting.

**Limitations:** This information is produced on a quarterly basis, and is aggregate at national level. Data from the self-employed and non-profit organizations are not included.

**Level of specificity:** These data are available in aggregated form at the national and state level. 

### The Job Opening and Labor Turnover Survey (JOLTS)

<http://www.bls.gov/jlt/>

This program under the BLS provides statistics on new openings, hires, and separations. The JOLTS serves as a demand-side indicator of labor shortages at the national level. (U.S. Bureau of Labor Statistics 2014)

**Strengths:** These data are released monthly. The JOLTS collects data on total employment, job openings, hires, quits, layoffs and discharges. It can be used for studying industry trends, education, and job training purposes.

**Limitations:** It includes nonagricultural industries only. 

**Level of specificity:** JOLTS data are available at the industry level.



### The Current Population Survey (CPS)

<http://www.bls.gov/cps/> 

The CPS is a monthly household survey supported jointly by the U.S. Census Bureau and the U.S. Bureau of Labor Statistics. It is the primary source of labor market economic statistics, such as employment, unemployment, and wages by industry, occupation, and demographic characteristics. (U.S. Bureau of Labor Statistics 2017b)

**Strengths:** The CPS provides monthly employment and unemployment data classified by a variety of demographic, social, and economic characteristics. This includes information that may be pertinent to VR, such as educational attainment and disability status.

**Limitations:** Disability status is self-reported, which may have an impact on the quality of the data. Sampling strategies are complex but were designed for national estimates and therefore reliable estimates cannot be made at the county level. Many counties are not included in the sample.

**Level of specificity:** CPS data are produced at the state level, and for 12 of the largest metropolitan statistical areas. 

### The National Compensation Survey (NCS)

<http://www.bls.gov/ncs/ect/>

The NCS is a survey conducted by the Office of Compensation Levels and Trends, which provides the following statistics:
- Quarterly changes in employer costs: Employment Cost Index (ECI). The ECI shows changes in wages and salaries, and benefit costs in addition to showing changes in total compensation.

- Quarterly employer cost levels: Employer Costs for Employee Compensation (ECEC). The ECEC is a quarterly survey that shows total compensation costs using these variables: wages and salaries; total benefit costs; separate benefit costs for broad benefit categories such as paid leave, supplemental pay, insurance, retirement, and savings; and legally required benefits. 

- Incidence and provisions of employee benefits, such as the average number of paid holidays provided to employees each year. (U.S. Bureau of Labor Statistics 2013)

**Strengths:** The ECI presents data as a total for all workers, and separately for private industry and for state and local government workers. Unlike the CPS, which is administered to a member of a household, this survey is administered to business establishments. Thus, the NCS may help you determine what the acceptable wage is for a particular position in a particular industry or occupational group. It can provide insight on an employer that you may not be able to determine by visiting their website. Occupations are classified using the Standard Occupational Classification system.

**Limitations:** Not all occupations within a given establishment are selected due to the method used in data collection by the NCS. The NCS uses Probability Selection of Occupations as their method of choice. It allows the NCS staff to select a particular occupation within the establishment. Occupations with the highest number of individuals are more likely to be selected.

**Level of specificity:** The ECI reports changes by industry, occupational group, union and nonunion status, and census region and division, for 15 large metropolitan areas and the nation. 

### The Employment Projections (EP)

<http://www.bls.gov/emp/>

The EP program produces 10-year projections of industry and occupational employment outlook. The latest projections are for the period of 2012–2022. This group also produces an annual Occupational Outlook Handbook, which contains national-level analysis based on the employment projections. (U.S. Bureau of Labor Statistics 2017a)

**Strengths:** The EP includes occupational profiles for the vast majority of employment settings. It provides education, related work experience, and on-the-job training requirements for a particular occupation.

**Limitations:** Economic, employment, and labor force projections are updated every other year. The EP does not produce short-term projections. These projections are not to be confused with the short and long-term projections compiled by your state’s department of labor. 

**Level of specificity:** Employment projections are provided at the national level. 

### O*NET Online

<http://www.onetcenter.org/>

The Occupational Information Network (O*NET) program is a comprehensive database of worker attributes and job characteristics and is compiled and managed by the Employment and Training Administration. Its interactive user interface contains standardized descriptions of different occupations. Such data help with career exploration and counseling, education, employment, training activities, and career decision-making.

**Strengths:** The data collected and processed by O*NET is available at no cost, and is continuously updated. The website also has a suite of career exploration tools. These can be used by VR to assist clients that want to choose a career or are considering a career change.

**Limitations:** O*NET data are heavily used by VR agencies and vendor organizations. One disclaimer is that data or career assessments included may have not undergone rigorous validity testing particularly for persons with disabilities. Access to the related instruments requires internet access and may require proficiency with information technology.

**Level of Specificity:** These data are available at the regional, state, and national levels.


## The United States Census Bureau and The U.S. Department of Commerce

The Census Bureau is the primary source of population demographics. The Census conducts large-scale nationwide data collection with advanced sampling methodologies that provide official national and subnational-level measures.

### Longitudinal Employer-Household Dynamics (LEHD)

<http://lehd.ces.census.gov/>

The LEHD program is part of the Center for Economic Studies at the U.S. Census Bureau. Through the Local Employment Dynamics (LED) Partnership, states have agreed to share unemployment insurance earnings data and participate in the Quarterly Census of Employment and Wages. These data are then combined with numerous administrative data, censuses, and surveys in order to create statistics on employment, earnings, and job flow in a specific geography and industry for different demographic groups. These data are used to create anonymized data on workers’ employment, and the LEHD Origin-Destination Employment Statistics (LODES). Industry-level data are available under the LEHD program, under Industry Focus	– <http://lehd.ces.census.gov/applications/industry_focus.html>.

**Strengths:** The LEHD program produces data that can be used by states and local authorities to make informed decisions about their economies.

**Limitations:** Some of the data collected by the LEHD program is considered to be confidential, and is only available to qualified researchers with approved projects through restricted access use in Census Research Data Centers.

**Level of specificity:** LEHD data are available at the state level.

### The Economic Census

<https://www.census.gov/programs-surveys/economic-census.html>

The Economic Census is the U.S. Government’s official measure of American business and economy. The Economic Census is the most comprehensive source of information about American businesses from the national to the local level. Published statistics include more than 1000 types of industries, 15,000 products, every state, over 3, 000 counties, 15,000 cities and towns, and Puerto Rico and other U.S. Island Areas. The most recent Economic Census was conducted in 2012. Primarily the economic census contains data on number establishments, revenue, annual payroll ($ value), and number of paid employees on payroll. This data is available across all sectors. These data are generally used for planning purposes by government agencies as well as by businesses. The Economic Census is also used to evaluate market share and new business opportunities. 

**Strengths:** Economic Census data are used by businesses to identify opportunities for growth. Having such an insight will allow VR to target businesses in their state that are planning to expand. These data can also be used to compare different communities. 

**Limitations:** The Economic Census is conducted every five years, in years ending in 2 and, and it does not census forms to most very small firms.

**Level of specificity:** Data are typically available at six levels of geographical specificity: National, States, Metro Areas, Counties, Places, and at ZIP Codes level.

### Business Dynamics Statistics (BDS)

<https://www.census.gov/ces/dataproducts/bds/>

The Business Dynamics Statistics (BDS) is a source of annual statistics on the 'business dynamics' (such as job creation and destruction, establishment births and deaths, and firm startups and shutdowns) for the economy and these data are aggregated by establishment and firm characteristics. The Longitudinal Business Database (LBD) <https://www.census.gov/ces/dataproducts/datasets/lbd.html> is the source of BDS. The LBD is a confidential database available to qualified researchers through secure Federal Statistical Research Data Centers <https://www.census.gov/fsrdc>. Using BDS, one can track business growth and decline in a given region.

**Strengths:** The BDS provides information on establishment openings, job expansions, and number of startups within a region. This information can help VR professions to identify industries that expanding and creating more jobs in the state. Business relations personnel at VR might find this data useful in identifying industry sectors and establishments that are growing and are seeking skilled employees.

**Limitations:** Self-employed, agricultural sectors, and most government establishments are not included in this dataset.

**Level of specificity:** Data are available at the state, metro/non-metro, and at Metropolitan Statistical Area level. 
