---
title: "Innovative Strategies"
author: "KartikTrivedi"
date: "November 28, 2017"
output:
    bookdown::gitbook: default
documentclass: book
---

# Existing Innovative Strategies

There are already some innovative strategies for LMI Integration used by VR Agencies. There are examples of how VR agencies are using traditional LMI, real-time LMI and labor market intelligence as a part of their workflow. Following three examples use different sources of LMI to best fit their needs. 

## The Alabama Department of Rehabilitation Services (ADRS) Dashboard

<http://www.rehab.alabama.gov/>

A dashboard is a tool that provides “critical” data accessible quickly similar to GPS systems in cars that store massive amounts of data, but pull relevant data to provide immediate directions. ADRS’s dashboard is integrating all three forms of LMI (Traditional, Real Time, and ADRS LMI Intelligence Data). 



## Vermont Division of Vocational Rehabilitation’s (VDVR) “Jobsville” Model 

<http://vocrehab.vermont.gov/>

As a part of VDVR’s Jobsville model, VR counselors share client goals with Business Specialists. Business Specialists provide the labor market intelligence by sharing current employment opportunities in local businesses. 



## The Career Index Plus 

<https://www.thecareerindex.com/dsp_intro.cfm>

The Career Index Plus compares thousands of data points with the customer’s background, needs and circumstances in mind to produce a unique and easy to understand summary of pros and cons along with detailed support information for a given career choice. As a freely available tool, The Career Index Plus can be used by a counselor as well as person looking for employment. The Career Index Plus does not collect or analyze any data by itself, it uses a variety of tools which it integrates with real time local labor market information as well as local job openings from thousands of online job boards and present the data in an user friendly interface. 


